name = "ArmaRAMDb"
author = "IDSolutions"
prefix = "ramdb"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.json",
    "*.paa",
    "*.so",
    "docs/**",
    "ArmaRAMDb_x64.dll",
    "ArmaRAMDb_x64.so",
    "config.xml",
    "ramdb_version.json",
    "LICENSE",
    "mod.cpp",
    "README.md"
]

[version]
git_hash = 0