name = "ArmaRAMDb"
author = "IDSolutions"
prefix = "ramdb"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "*.json",
    "config.xml",
    "mod.cpp",
    "README.md",
    "LICENSE",
    "icon_64_ca.paa",
    "icon_128_ca.paa",
    "icon_128_highlight_ca.paa",
    "title_co.paa",
    "ArmaRAMDb_x64.dll",
    "ArmaRAMDb_x64.so"
]

[version]
git_hash = 0